spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redisson:
    address: 192.168.19.131:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
dubbo:
  application:
    name: promo-service
    owner: ciggar
  protocol:
    name: dubbo
    port: 20889
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://localhost:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.mall.promo.service

