dubbo:
  application:
    name: gateway
    owner: ciggar
  registry:
    address: zookeeper://localhost:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://localhost:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.cskaoyan.gateway
captchaFlag : false
spring:
  resources:
    static-locations: file:/project3/server/resources/pic
  redisson:
    address: 192.168.19.131:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4