dubbo:
  application:
    name: gateway
    owner: ciggar
  registry:
    address: zookeeper://192.168.5.96:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.5.96:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.cskaoyan.gateway
captchaFlag : false
