spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/csmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redisson:
    address: 192.168.19.130:6379
    timeout: 3000
    database: 0
dubbo:
  application:
    name: pay-com.mall.pay.service
    owner: ciggar
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://127.0.0.1:2181
    check: true
    group: dubbo-dev
    simplified: true
  scan:
    base-packages: com.mall.pay.service

